// <auto-generated />
using System;
using CoffeeShopManager.DAL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CoffeeShopManager.DAL.Migrations
{
    [DbContext(typeof(CoffeeShopDbContext))]
    [Migration("20260916072920_AddKhuyenMai")]
    partial class AddKhuyenMai
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("CoffeeShopManager.DAL.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MaNV")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MaNV");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("CoffeeShopManager.DAL.Entities.Ban", b =>
                {
                    b.Property<int>("MaBan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("TenBan")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("MaBan");

                    b.ToTable("Ban");

                    b.HasData(
                        new
                        {
                            MaBan = 1,
                            TenBan = "Bàn 1",
                            TrangThai = "Trống"
                        },
                        new
                        {
                            MaBan = 2,
                            TenBan = "Bàn 2",
                            TrangThai = "Trống"
                        },
                        new
                        {
                            MaBan = 3,
                            TenBan = "Bàn 3",
                            TrangThai = "Trống"
                        },
                        new
                        {
                            MaBan = 4,
                            TenBan = "Bàn 4",
                            TrangThai = "Trống"
                        },
                        new
                        {
                            MaBan = 5,
                            TenBan = "Bàn 5",
                            TrangThai = "Trống"
                        },
                        new
                        {
                            MaBan = 6,
                            TenBan = "Bàn VIP",
                            TrangThai = "Trống"
                        });
                });

            modelBuilder.Entity("CoffeeShopManager.DAL.Entities.ChiTietHD", b =>
                {
                    b.Property<int>("MaChiTiet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaHD")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaMon")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SoLuong")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ThanhTien")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MaChiTiet");

                    b.HasIndex("MaHD");

                    b.HasIndex("MaMon");

                    b.ToTable("ChiTietHD");
                });

            modelBuilder.Entity("CoffeeShopManager.DAL.Entities.HoaDon", b =>
                {
                    b.Property<int>("MaHD")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DiemSuDung")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaBan")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MaKH")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MaKM")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MaNV")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PhuongThucThanhToan")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("TenKH")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ThoiGianTao")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TienGiamKhuyenMai")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TienGiamTuDiem")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("MaHD");

                    b.HasIndex("MaBan");

                    b.HasIndex("MaKH");

                    b.HasIndex("MaKM");

                    b.HasIndex("MaNV");

                    b.ToTable("HoaDon");
                });

            modelBuilder.Entity("CoffeeShopManager.DAL.Entities.HoaDonKhuyenMai", b =>
                {
                    b.Property<int>("MaHDKM")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaHD")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaKM")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("SoTienGiam")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ThoiGianApDung")
                        .HasColumnType("TEXT");

                    b.HasKey("MaHDKM");

                    b.HasIndex("MaHD");

                    b.HasIndex("MaKM");

                    b.ToTable("HoaDonKhuyenMai");
                });

            modelBuilder.Entity("CoffeeShopManager.DAL.Entities.KhachHang", b =>
                {
                    b.Property<int>("MaKH")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DiemTichLuy")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<string>("TenKH")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("MaKH");

                    b.ToTable("KhachHang");

                    b.HasData(
                        new
                        {
                            MaKH = 1,
                            DiemTichLuy = 0,
                            Email = "",
                            SoDienThoai = "",
                            TenKH = "Khách lẻ"
                        },
                        new
                        {
                            MaKH = 2,
                            DiemTichLuy = 100,
                            Email = "pvd@gmail.com",
                            SoDienThoai = "0904567890",
                            TenKH = "Phạm Văn D"
                        },
                        new
                        {
                            MaKH = 3,
                            DiemTichLuy = 250,
                            Email = "hte@gmail.com",
                            SoDienThoai = "0905678901",
                            TenKH = "Hoàng Thị E"
                        });
                });

            modelBuilder.Entity("CoffeeShopManager.DAL.Entities.KhuyenMai", b =>
                {
                    b.Property<int>("MaKM")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DaKichHoat")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("GiaTriGiam")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("HoaDonToiThieu")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("LoaiKhuyenMai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("LoaiMon")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("MaMon")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MaNguoiTao")
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<string>("MoTa")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("TEXT");

                    b.Property<int>("SoLanDaSuDung")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SoLanSuDungToiDa")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TenKhuyenMai")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("MaKM");

                    b.HasIndex("MaMon");

                    b.ToTable("KhuyenMai");
                });

            modelBuilder.Entity("CoffeeShopManager.DAL.Entities.Mon", b =>
                {
                    b.Property<int>("MaMon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Loai")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("TenMon")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("MaMon");

                    b.ToTable("Mon");

                    b.HasData(
                        new
                        {
                            MaMon = 1,
                            DonGia = 25000m,
                            Loai = "Cà phê",
                            TenMon = "Cà phê đen"
                        },
                        new
                        {
                            MaMon = 2,
                            DonGia = 30000m,
                            Loai = "Cà phê",
                            TenMon = "Cà phê sữa"
                        },
                        new
                        {
                            MaMon = 3,
                            DonGia = 30000m,
                            Loai = "Cà phê",
                            TenMon = "Bạc xỉu"
                        },
                        new
                        {
                            MaMon = 4,
                            DonGia = 45000m,
                            Loai = "Cà phê",
                            TenMon = "Cappuccino"
                        },
                        new
                        {
                            MaMon = 5,
                            DonGia = 35000m,
                            Loai = "Trà",
                            TenMon = "Trà đào cam sả"
                        },
                        new
                        {
                            MaMon = 6,
                            DonGia = 40000m,
                            Loai = "Trà",
                            TenMon = "Trà sữa trân châu"
                        },
                        new
                        {
                            MaMon = 7,
                            DonGia = 35000m,
                            Loai = "Nước ép",
                            TenMon = "Nước cam ép"
                        },
                        new
                        {
                            MaMon = 8,
                            DonGia = 40000m,
                            Loai = "Nước ép",
                            TenMon = "Sinh tố bơ"
                        },
                        new
                        {
                            MaMon = 9,
                            DonGia = 20000m,
                            Loai = "Đồ ăn nhẹ",
                            TenMon = "Bánh mì"
                        },
                        new
                        {
                            MaMon = 10,
                            DonGia = 25000m,
                            Loai = "Đồ ăn nhẹ",
                            TenMon = "Bánh ngọt"
                        });
                });

            modelBuilder.Entity("CoffeeShopManager.DAL.Entities.NhanVien", b =>
                {
                    b.Property<int>("MaNV")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CaLam")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<string>("TenNV")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("MaNV");

                    b.ToTable("NhanVien");

                    b.HasData(
                        new
                        {
                            MaNV = 1,
                            CaLam = "Sáng",
                            Email = "nva@coffee.com",
                            SoDienThoai = "0901234567",
                            TenNV = "Nguyễn Văn A"
                        },
                        new
                        {
                            MaNV = 2,
                            CaLam = "Chiều",
                            Email = "ttb@coffee.com",
                            SoDienThoai = "0902345678",
                            TenNV = "Trần Thị B"
                        },
                        new
                        {
                            MaNV = 3,
                            CaLam = "Tối",
                            Email = "lvc@coffee.com",
                            SoDienThoai = "0903456789",
                            TenNV = "Lê Văn C"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("CoffeeShopManager.DAL.Entities.ApplicationUser", b =>
                {
                    b.HasOne("CoffeeShopManager.DAL.Entities.NhanVien", "NhanVien")
                        .WithMany()
                        .HasForeignKey("MaNV")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("CoffeeShopManager.DAL.Entities.ChiTietHD", b =>
                {
                    b.HasOne("CoffeeShopManager.DAL.Entities.HoaDon", "HoaDon")
                        .WithMany("ChiTietHDs")
                        .HasForeignKey("MaHD")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoffeeShopManager.DAL.Entities.Mon", "Mon")
                        .WithMany("ChiTietHDs")
                        .HasForeignKey("MaMon")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HoaDon");

                    b.Navigation("Mon");
                });

            modelBuilder.Entity("CoffeeShopManager.DAL.Entities.HoaDon", b =>
                {
                    b.HasOne("CoffeeShopManager.DAL.Entities.Ban", "Ban")
                        .WithMany("HoaDons")
                        .HasForeignKey("MaBan")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CoffeeShopManager.DAL.Entities.KhachHang", "KhachHang")
                        .WithMany("HoaDons")
                        .HasForeignKey("MaKH")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CoffeeShopManager.DAL.Entities.KhuyenMai", "KhuyenMai")
                        .WithMany()
                        .HasForeignKey("MaKM")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CoffeeShopManager.DAL.Entities.NhanVien", "NhanVien")
                        .WithMany("HoaDons")
                        .HasForeignKey("MaNV")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Ban");

                    b.Navigation("KhachHang");

                    b.Navigation("KhuyenMai");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("CoffeeShopManager.DAL.Entities.HoaDonKhuyenMai", b =>
                {
                    b.HasOne("CoffeeShopManager.DAL.Entities.HoaDon", "HoaDon")
                        .WithMany("HoaDonKhuyenMais")
                        .HasForeignKey("MaHD")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoffeeShopManager.DAL.Entities.KhuyenMai", "KhuyenMai")
                        .WithMany("HoaDonKhuyenMais")
                        .HasForeignKey("MaKM")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HoaDon");

                    b.Navigation("KhuyenMai");
                });

            modelBuilder.Entity("CoffeeShopManager.DAL.Entities.KhuyenMai", b =>
                {
                    b.HasOne("CoffeeShopManager.DAL.Entities.Mon", "Mon")
                        .WithMany()
                        .HasForeignKey("MaMon")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Mon");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("CoffeeShopManager.DAL.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("CoffeeShopManager.DAL.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoffeeShopManager.DAL.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("CoffeeShopManager.DAL.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CoffeeShopManager.DAL.Entities.Ban", b =>
                {
                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("CoffeeShopManager.DAL.Entities.HoaDon", b =>
                {
                    b.Navigation("ChiTietHDs");

                    b.Navigation("HoaDonKhuyenMais");
                });

            modelBuilder.Entity("CoffeeShopManager.DAL.Entities.KhachHang", b =>
                {
                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("CoffeeShopManager.DAL.Entities.KhuyenMai", b =>
                {
                    b.Navigation("HoaDonKhuyenMais");
                });

            modelBuilder.Entity("CoffeeShopManager.DAL.Entities.Mon", b =>
                {
                    b.Navigation("ChiTietHDs");
                });

            modelBuilder.Entity("CoffeeShopManager.DAL.Entities.NhanVien", b =>
                {
                    b.Navigation("HoaDons");
                });
#pragma warning restore 612, 618
        }
    }
}
